controllers/AjaxController.php
<?php

/**
 * Created by PhpStorm.
 * User: tin
 * Date: 26.11.2017
 * Time: 21:55
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Filter;

class AjaxController extends Controller {

    public function actionGetFullInfo() {
        if (!isset($_POST['id']) || empty($_POST['id'])) {
            echo '';
            Yii::$app->end();
        }
        $data = \app\models\Event::find()->where(['id' => $_POST['id']])->one();
        if (!$data) {
            echo '';
            Yii::$app->end();
        }
        $text = preg_replace('/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)/i', '<a href="$1" target="_blank">$1</a>', $data->description);
        $text = preg_replace('/<a href="([A-Za-z0-9_.]+@[A-Za-z0-9_.]+)"/i', '<a href="mailto:$1"', $text);
        echo json_encode([
            'name' => $data->name,
            'html' => nl2br($text),
        ]);
        Yii::$app->end();
    }
    
    public function actionGetFullInfoModal() {
        if (!isset($_POST['id']) || empty($_POST['id'])) {
            echo '';
            Yii::$app->end();
        }
        $data = \app\models\Event::find()->where(['id' => $_POST['id']])->one();
        if (!$data) {
            echo '';
            Yii::$app->end();
        }
        $text = preg_replace('/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)/i', '<a href="$1" target="_blank">$1</a>', $data->description);
        $text = preg_replace('/<a href="([A-Za-z0-9_.]+@[A-Za-z0-9_.]+)"/i', '<a href="mailto:$1"', $text);
        $text = nl2br($text);
        echo json_encode([
            'name' => $data->name,
            'html' => $this->renderPartial('fullInfoModal', [
                        'data' => $data,
                        'text' => $text,
                    ])
        ]);
    }

    public function actionGetEventContent() {
        $filter = new Filter;
        $filter->attributes = json_decode($_POST['filterData'], true);
        $city = \app\models\City::detectSavedCity(true);
        $events = \app\models\Event::find()->joinWith('categoriesIds')
                ->where(['city_id' => $city->id])
                ->andWhere(['isDraft' => 0]);
        if (empty($filter->meeting_date) && (empty($filter->time_begin) || $filter->time_begin == '00:00')) {
	    $events = $events->andWhere(['OR', ['>=', 'CONCAT(meeting_date, " ",time_begin)', date('Y-m-d H:i:s')], ['AND', ['>=','meeting_date',date('Y-m-d')], 'no_time' => 1]]);
            //$events = $events->andWhere(['>=', 'CONCAT(meeting_date, " ",time_begin)', date('Y-m-d H:i:s')]);
        } elseif (empty($filter->meeting_date) && !empty($filter->time_begin) && $filter->time_begin != '00:00') {
            $events = $events->andWhere(['>=', 'meeting_date', date('Y-m-d')]);
            $events = $events->andWhere(['>=', 'time_begin', $filter->time_begin]);
        } elseif (!empty($filter->meeting_date)) {
            $events = $events->andWhere(['>=', 'meeting_date', $filter->meeting_date]);
            if (!empty($filter->time_begin))
                $events = $events->andWhere(['>=', 'time_begin', $filter->time_begin]);
        }
        if (!empty($filter->category))
            $events = $events->andWhere(['rel_event_to_category.event_category_id' => $filter->category]);
        $events = $events->orderBy('meeting_date, time_begin')
                ->limit(Yii::$app->params['limit_objects_on_page'])
                ->offset($_POST['startFrom'])
                ->groupBy('id')
                ->all();
        return $this->renderPartial('../site/events', [
                    'events' => $events,
                    'city' => $city,
                    'date' => Yii::$app->request->post('lastDate', NULL),
        ]);
    }
    
    public function actionSendNewCategory() {
        if(!Yii::$app->request->isAjax) {
            echo json_encode(['status' => false, 'textMessage' => 'В процессе произошла ошибка.']);
            Yii::$app->end();
        }
        $category_name = Yii::$app->request->post('category_name', NULL);
        if($category_name == NULL){
            echo json_encode(['status' => false, 'textMessage' => 'Название категории не может быть пустым.']);
            Yii::$app->end();
        }
        
        $subject = "Запрос на добавление категории";
        
        $send_msg = Yii::$app
            ->mailer
            ->compose(
                ['text' => 'sendNewCategory'],
                ['category_name' => $category_name, 'user_id' => Yii::$app->user->id]
            )
            ->setFrom([Yii::$app->params['noreplyEmail'] => 'no-reply@'.Yii::$app->name])
            ->setTo(Yii::$app->params['supportEmail'])
            ->setSubject($subject)
            ->send();
        if($send_msg) {
            echo json_encode(['status' => true, 'textMessage' => 'Ваша заявка отправлена, вы можете пока сохранить свое мероприятие, как черновик. После добавления новой категории мы с вами свяжемся.']);
            Yii::$app->end();
        } else {
            echo json_encode(['status' => false, 'textMessage' => 'В процессе отправки сообщения произошла ошибка. Повторите запрос позднее.']);
            Yii::$app->end();
        }
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\SignupForm;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\Event;
use app\models\City;
use app\models\Filter;
use app\components\AuthHandler;

//'event' => 'event/list', - Удалить этот роут
class SiteController extends Controller {

    public function actions() {
        return [
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'onAuthSuccess'],
            ],
        ];
    }

    public function actionIndex() {
        $cookies = Yii::$app->getRequest()->getCookies();
        //Если нет города          
        if (!isset($_GET['city']) || empty($_GET['city'])) {
            if ($cookies->has('city') === true) {
                return $this->redirect('/' . $cookies['city']->value);
            } else {
                Yii::$app->getResponse()->getCookies()->add(new \yii\web\Cookie([
                    'name' => 'city',
                    'value' => 'obninsk',
                    'expire' => time() + 60 * 60 * 24 * 30,
                    'path' => '/',
                    'httpOnly' => false,
                ]));
                return $this->redirect('/obninsk');
            }
        } else {
            $city = \app\models\City::find()->where(['alias' => $_GET['city']])->one();
            if ($city) {
                if ($cookies->has('city') === true && $cookies['city']->value != $city->alias) {
                    Yii::$app->getResponse()->getCookies()->remove('city');
                    Yii::$app->getResponse()->getCookies()->add(new \yii\web\Cookie([
                        'name' => 'city',
                        'value' => $city->alias,
                        'expire' => time() + 60 * 60 * 24 * 30,
                        'path' => '/',
                        'httpOnly' => false,
                    ]));
                }
            } else {
                Yii::$app->getResponse()->getCookies()->add(new \yii\web\Cookie([
                    'name' => 'city',
                    'value' => 'obninsk',
                    'expire' => time() + 60 * 60 * 24 * 30,
                    'path' => '/',
                    'httpOnly' => false,
                ]));
                return $this->redirect('/' . $cookies['city']->value);
            }
        }
        //Обределяем режим работы мероприятия=1 или организации=2
        if ($cookies->has('mode') === false || !in_array($cookies['mode']->value, [1, 2])) {
            Yii::$app->getResponse()->getCookies()->add(new \yii\web\Cookie([
                'name' => 'mode',
                'value' => '1',
                'expire' => time() + 60 * 60 * 24 * 30,
                'path' => '/',
                'httpOnly' => false,
            ]));
            return $this->refresh();
        }

        $city = City::find()->where(['alias' => $_GET['city']])->one();

        $events = Event::find()->joinWith('categoriesIds')
                ->where(['city_id' => $city->id])
                ->andWhere(['isDraft' => 0]);
        $category_id = Yii::$app->request->get('category', null);
        if (empty(Yii::$app->request->get('category'))) {
            $filter = new Filter;
            if (empty($filter->meeting_date) && (empty($filter->time_begin) || $filter->time_begin == '00:00')) {
                //$events = $events->andWhere(['>=', 'CONCAT(meeting_date, " ",time_begin)', date('Y-m-d H:i:s')]);
		$events = $events->andWhere(['OR', ['>=', 'CONCAT(meeting_date, " ",time_begin)', date('Y-m-d H:i:s')], ['AND', ['>=','meeting_date',date('Y-m-d')], 'no_time' => 1]]);
            } elseif (empty($filter->meeting_date) && !empty($filter->time_begin) && $filter->time_begin != '00:00') {
                $events = $events->andWhere(['>=', 'meeting_date', date('Y-m-d')]);
                $events = $events->andWhere(['>=', 'time_begin', $filter->time_begin]);
            } elseif (!empty($filter->meeting_date)) {
                $events = $events->andWhere(['>=', 'meeting_date', $filter->meeting_date]);
                if (!empty($filter->time_begin))
                    $events = $events->andWhere(['>=', 'time_begin', $filter->time_begin]);
            }
            if (!empty($filter->category))
                $events = $events->andWhere(['rel_event_to_category.event_category_id' => $filter->category]);
        } else {
            $category_id = \app\models\EventCategory::find()->where(['alias' => Yii::$app->request->get('category')])->one()->id;
            $filter = new Filter;
            $filter = $filter->set_filter_by_category_link($category_id);
            $events = $events->andWhere(['>=', 'CONCAT(meeting_date, " ",time_begin)', date('Y-m-d H:i:s')]);
            $events = $events->andWhere([
                'rel_event_to_category.event_category_id' => $category_id
            ]);
        }
        $events = $events->orderBy('meeting_date, time_begin')
                ->limit(Yii::$app->params['limit_objects_on_page'])
                ->groupBy('id')
                ->all();
        //Если в урле у нас передается ID события начинаем вытаскивать по нему инфомацию из БД
        $event_id = Yii::$app->request->get('event_id', null);
        $event_info = null;
        $event_info_text = null;
        if ($event_id != null) {
            if (!Event::find()->where(['id' => $event_id])->exists()) {
                $event_info = null;
            } else {
                $event_info = Event::find()->where(['id' => $event_id])->one();
                $event_info_text = preg_replace('/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[.\!\/\\w]*))?)/i', '<a href="$1" target="_blank">$1</a>', $event_info->description);
                $event_info_text = preg_replace('/<a href="([A-Za-z0-9_.]+@[A-Za-z0-9_.]+)"/i', '<a href="mailto:$1"', $event_info_text);
                $event_info_text = nl2br($event_info_text);
            }
        }
        //Определяем мета теги
        if ($category_id == null && $event_id == null) {
            $this->view->title = 'Афиша мероприятий вашего города — ' . $city->name . ' — YOweekend.ru';
            $this->view->registerMetaTag([
                'name' => 'description',
                'content' => 'Афиша предстоящих мероприятий в городе ' . $city->name
            ]);
            $this->view->registerMetaTag([
                'name' => 'keywords',
                'content' => 'афиша мероприятий, мероприятия, события, куда сходить, ' . $city->name,
            ]);
        } elseif ($category_id != NULL) {
            $category = \app\models\EventCategory::find()->where(['id' => $category_id])->one();
            if ($category) {
                $this->view->title = $category->name . ' — Афиша мероприятий вашего города —' . $city->name . ' — YOweekend.ru';
                $this->view->registerMetaTag([
                    'name' => 'description',
                    'content' => 'Афиша предстоящих мероприятий в городе ' . $city->name . ' в категории ' . $category->name,
                ]);
                $this->view->registerMetaTag([
                    'name' => 'keywords',
                    'content' => 'афиша мероприятий, мероприятия, события, куда сходить, ' . $city->name . ', ' . $category->name,
                ]);
            }
        } elseif ($event_id != NULL) {
            if ($event_info) {
                $this->view->title = $event_info->name . ' — Афиша мероприятий вашего города — ' . $city->name . ' — YOweekend.ru';
                $this->view->registerMetaTag([
                    'name' => 'description',
                    'content' => mb_strimwidth($event_info->description, 0, 100, ''),
                ]);
                $this->view->registerMetaTag([
                    'name' => 'keywords',
                    'content' => $event_info->name,
                ]);
            }
        }

        if ($event_info != NULL)
            $this->view->title = $event_info->name . ' — ' . $this->view->title;

        return $this->render('index', [
                    'events' => $events,
                    'city' => $city,
                    'filter_query' => json_encode($filter->attributes),
                    'filter' => $filter,
                    'event_info' => $event_info,
                    'event_info_text' => $event_info_text,
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        $this->view->title = 'Авторизация — YOweekend.ru';
        $this->layout = 'main_mini';
        return $this->render('login', [
                    'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionRegister() {
        $this->view->title = 'Регистрация — YOweekend.ru';
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
        $this->layout = 'main_mini';
        return $this->render('register', [
                    'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset() {
        $this->view->title = 'Сброс пароля — YOweekend.ru';

views/site/_activeFilter.php
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <ul class="breadcrumb">
      <li>Выбранные категории: <span class="filter-active-params">
                <?= implode(', ',$filter->getStringCategories())?>
      </span></li>
      <? if(!empty($filter->meeting_date)): ?>
        <li>Начиная с: <span class="filter-active-params"><?= Yii::$app->formatter->asDate($filter->meeting_date, 'd MMMM yyyy') ?></span></li>
      <? else: ?>
        <li>Начиная с: <span class="filter-active-params"><?= Yii::$app->formatter->asDate(date('Y-m-d'), 'd MMMM yyyy') ?></span></li>
      <? endif; ?>
      <? if(!empty($filter->time_begin)): ?>
        <? ($filter->time_begin == '00:00') ? $timebegin = 'Не важно' : $timebegin = $filter->time_begin ?>
        <li>Время начала с: <span class="filter-active-params"><?= $timebegin ?></span></li>
      <? endif; ?>
    </ul>
</div>

views/site/_event.php
<?
    if($city == NULL)
        $city = $e->city->name;
?>
<div class="card col-lg-3 col-md-4 col-sm-4 col-xs-6">
    <div class="thumbnail">
        <div class="image-preview">
            <img src="<?= $e->image_preview ?>" data-full-img="<?= $e->image_original ?>" data-address="<?= $city?>, <?= $e->address ?>" data-id="<?= $e->id ?>">
            <? if(!empty($e->address)): ?>
            <span class="address"><a href="#" class="openMap" data-address="<?= $city?>, <?= $e->address ?>" onclick="openMap($(this).attr('data-address'));return false;"><i class="fa fa-map-marker address-marker"></i><span class="address-text"><?= $e->address ?></span></a></span>
            <? endif; ?>
        </div>
        <div class="caption">
            <span class="icon-panel">
                <a class="share-icon" href="https://vk.com/share.php?url=http://<?= $_SERVER['SERVER_NAME'] ?>/<?= $e->city->alias?>/event_<?= $e->id ?>&title=<?= htmlspecialchars($e->name, ENT_QUOTES) ?>&image=<?= 'http://'.$_SERVER['SERVER_NAME'].str_replace('\\', '/', $e->image_original) ?>&noparse=true" target="_blank">
                    <i class="fa fa-share-alt"></i>
                </a>
                <!--<a href="#" class="share-icon"><i class="fa fa-share-alt"></i></a>-->
            </span>
            <span class="name"><a href="/<?= $e->city->alias?>/event_<?= $e->id ?>" class="open-event-window" data-id="<?= $e->id ?>" onclick="showFullInfo($(this).attr('data-id'), '/ajax/get-full-info-modal');return false;"><?= mb_strimwidth($e->name, 0, 60, '...') ?></a></span>
            <span class="link"><a href="<?= $e->link ?>" target="_blank"><?= mb_strimwidth($e->link, 0, 30, '...') ?></a></span>
            <? if($e->no_time == 0):?>
                <span class="datetime">
                    <strong class="strong-underline">Время:</strong> 
                    <?= Yii::$app->formatter->asTime($e->time_begin) ?>
                </span>
            <? else: ?>
                <span class="datetime">
                    <strong class="strong-underline">Время:</strong> 
                    Не указано
                </span>
            <? endif; ?>
            <?php
            if (empty($e->price) || $e->price == 0)
                $price = 'Бесплатно';
            else
                $price = $e->price . '<i class="fa fa-rub" aria-hidden="true"></i>';
            ?>
            <span class="money"><strong class="strong-underline">Вход:</strong> <?= $price ?></span>
            <span class="intro"><a href="#" class="showFullInfo" data-id="<?= $e->id ?>" onclick="showFullInfo($(this).attr('data-id'), '/ajax/get-full-info');return false;"><?= mb_strimwidth($e->description, 0, 100, '...') ?></a></span>
        </div>
    </div>
</div>

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/events.php
<? if(!isset($date)) $date = NULL; ?>
<? foreach($events as $e): ?>
    <? if($date == NULL || ($date != $e->meeting_date && $date != Yii::$app->formatter->asDate($e->meeting_date, 'd MMMM yyyy'))): ?>
        <? $date = $e->meeting_date ?>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 date-label-area">
            <div class="date-label"><?= Yii::$app->formatter->asDate($date, 'd MMMM yyyy') ?></div>
        </div>
    <? endif; ?>
    <?= Yii::$app->view->render('_event', ['e' => $e, 'city' => (isset($city)) ? $city->name : NULL]) ?>
<? endforeach; ?>

views/site/index.php
<? if(Yii::$app->user->isGuest): ?>
    <? $onclick_title = 'Требуется авторизация'; ?>
    <? $onclick_message = "Для того что бы доавблять свои мероприятия вам необходимо <a href=\'/login\'>войти</a> или <a href=\'/register\'>зарегистрироваться</a>.";?>
<? else: ?>
    <? //$onclick_title = 'Что вы хотите добавить?'; ?>
    <? //$onclick_message = "Выберите действие:<br /><a href=\'/event/add\'>добавить мероприятие</a> или <a href=\'/point/add\'>добавить место</a>?";?>
<? endif; ?>
<div class="col-lg-3 col-md-4 col-sm-5 col-xs-12 add-event-not-register">
    <? if(isset($onclick_message) && !empty($onclick_message)): ?>
    <button type="button" class="btn btn-block btn-success btn-sm"
            onclick="show_info_modal('<?= $onclick_title ?>', '<?= $onclick_message ?>')">
        <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Добавить мероприятие
    </button>
    <? else: ?>
    <button type="button" class="btn btn-block btn-success btn-sm"
            onclick="window.location.href='/event/add'">
        <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;Добавить мероприятие
    </button>
    <? endif; ?>
</div>
<div class="clear" style="clear: both"></div>
<?= Yii::$app->view->render('_activeFilter', ['filter' => $filter]) ?>
<input type="hidden" name="filter_data" value='<?= $filter_query ?>'>
<?= Yii::$app->view->render('events', ['events' => $events, 'city' => $city]) ?>
<?php if($event_info != null): ?>
        <div class="modal fade in" id="event_modal_page">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <a href="/<?= $city->alias ?>"><button type="button" class="close" aria-label="Close">
                                <span aria-hidden="true">×</span></button></a>
                        <h4 class="modal-title"><?= $event_info->name ?></h4>
                    </div>
                    <div class="modal-body">
                        <?= Yii::$app->view->renderFile(dirname(__FILE__) . '/../ajax/fullInfoModal.php', [
                            'data' => $event_info,
                            'text' => $event_info_text,
                        ])?>
                    </div>
                    <div class="modal-footer">
                        <a href="/<?= $city->alias ?>"><button type="button" class="btn btn-default pull-left">Закрыть</button></a>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div> 
<script>
    window.onload = function() {
        $("#event_modal_page").modal('show');
        $("#event_modal_page").on('hidden.bs.modal', function(){
           window.location.href = '/<?= $city->alias ?>'; 
        });
    }
</script>
<?php endif; ?>

views/site/login.php
<?php
    use yii\helpers\Html;
    use yii\bootstrap\ActiveForm;
?>
<div class="login-box">
    <div class="register-logo">
        <a href="/"><img src="/img/logo.png" /></a>
    </div>
    <div class="login-box-body">
        <? if(!empty(Yii::$app->session->getFlash('success'))): ?>
            <div class="callout callout-info">
                <h4><i class="fa fa-info"></i> Успех:</h4>
                <?= Yii::$app->session->getFlash('success')?>
            </div>
        <? endif; ?>
        <? if(!empty(Yii::$app->session->getFlash('error'))): ?>
            <div class="callout callout-info">
                <h4><i class="fa fa-info"></i> Успех:</h4>
                <?= Yii::$app->session->getFlash('error')?>
            </div>
        <? endif; ?>
        <?php $form = ActiveForm::begin(['id' => 'login']); ?>
        <div class="form-group has-feedback">
            <?= $form->field($model, 'username', [
                'template' => '{input}{error}{hint}<span class="glyphicon glyphicon-user form-control-feedback"></span>'
            ])->textInput(['autofocus' => false, 'placeholder' => 'Логин']) ?>
        </div>
        <div class="form-group has-feedback">
            <?= $form->field($model, 'password', [
                'template' => '{input}{error}{hint}<span class="glyphicon glyphicon-lock form-control-feedback"></span>'
            ])->passwordInput(['autofocus' => false, 'placeholder' => 'Пароль']) ?>
        </div>
        <div class="row">
            <div class="col-xs-8">
                <div class="checkbox icheck">
                        <?= $form->field($model, 'rememberMe', [
                            'template' => '{input}'
                        ])->checkbox() ?>
                </div>
            </div>
            <!-- /.col -->
            <div class="col-xs-4">
                <button type="submit" class="btn btn-primary btn-block btn-flat">Войти</button>
            </div>
            <!-- /.col -->
        </div>
        <?php ActiveForm::end(); ?>

        <div class="social-auth-links text-center">
            <a href="/site/auth?authclient=vkontakte" class="btn btn-block btn-social btn-vk btn-flat"><i class="fa fa-vk"></i> Войти с помощью VK</a>
        </div>
        <!-- /.social-auth-links -->
        <a href="/">Вернуться на сайт</a><br>
        <a href="/request-password-reset">Забыли пароль?</a><br>
        <a href="/register" class="text-center">Зарегистрироваться</a>

    </div>
    <!-- /.login-box-body -->
</div>