models/Event.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "events".
 *
 * @property integer $id
 * @property string $name
 * @property string $image_original
 * @property string $image_preview
 * @property string $link
 * @property integer $city_id
 * @property string $address
 * @property string $meeting_date
 * @property string $time_begin
 * @property integer $no_time
 * @property integer $price
 * @property string $description
 * @property integer $isDraft
 * @property integer $isVkSend
 */
class Event extends \yii\db\ActiveRecord
{
    
    public $image;
    public $category_ids;
    public $x1, $x2, $y1, $y2;
    /**
     * @inheritdoc
     */
    
    public function init() {
        $this->image_original = '/img/temp_image.png';
        $this->image_preview = '/img/temp_image.png';
        $this->x1 = 0;
        $this->x2 = 299;
        $this->y1 = 0;
        $this->y2 = 299;
    }


    public static function tableName()
    {
        return 'events';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'city_id', 'meeting_date', 'time_begin', 'category_ids', 'user_id', 'address'], 'required'],
            [['meeting_date'], 'date'],
            [['time_begin'], 'time'],
            [['city_id', 'price', 'isDraft', 'isVkSend', 'x1', 'x2', 'y1', 'y2', 'user_id', 'no_time'], 'integer'],
            [['meeting_date', 'time_begin', 'no_time'], 'safe'],
            [['description'], 'string'],
            [['name', 'image_original', 'image_preview', 'link', 'address'], 'string', 'max' => 255],
            [['link'], 'url'],
            ['x1', function ($attribute, $params) {
                if(abs($this->x1-$this->x2) > 300 || abs($this->y1-$this->y2) > 300)
                    $this->addError($attribute, 'Выбранная область изображения больше чем разрешено. Выделите правильную область.');
            }],
            ['image_original', function($attribute, $params){
                if(!file_exists($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . $this->image_original) || !file_exists($_SERVER['DOCUMENT_ROOT'] . DIRECTORY_SEPARATOR . $this->image_preview)) 
                    $this->addError($attribute, 'При преобразовании изображения возникла ошибка.');
            }],
            ['category_ids', function($attribute, $params) {
                if(count($this->category_ids) > 3) 
                    $this->addError($attribute, 'Вы можете выбрать только 3 категории.');
            }],
            [['create_date', 'update_date'], 'safe'],
        ];
    }
    
    public function getCategoriesIds()
    {
        return $this->hasMany(RelEventToCategory::className(), ['event_id' => 'id']);
    }
    
    public function getCity() {
        return $this->hasOne(City::className(), ['id' => 'city_id']);
    }


    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название мероприятия',
            'image_original' => 'Оригинал изображения',
            'image_preview' => 'Превью изображения',
            'link' => 'Ссылка',
            'city_id' => 'Город',
            'address' => 'Адрес',
            'meeting_date' => 'Дата мероприятия',
            'time_begin' => 'Время начала мероприятия',
            'no_time' => 'Не показывать время на сайте (не желательно)',
            'price' => 'Стоимость',
            'description' => 'Описание (форматирование сохраняется, ссылки будут активны)',
            'isDraft' => 'Черновик',
            'isVkSend' => 'Статус экспорта в VK',
            'category_ids' => 'Категории (не боллее 3-х)',
        ];
    }
    
    public function getPreviewSize($imagesize) {        
        $ratio = $imagesize[0]/$imagesize[1];
        $otions = [];
        if ($imagesize[0] > $imagesize[1]) {
            $options['height'] = 300;
            $options['width'] = round(300*$ratio);
        }
        elseif ($imagesize[1] > $imagesize[0]) {
            $options['width'] = 300;
            $options['height'] = round(300/$ratio);
        } else {
            $options['width'] = 300;
            $options['height'] = 300;
        }

        return $options;
    }
    
    public function getRealImgSize($filename) {
        $size = getimagesize($_SERVER['DOCUMENT_ROOT'] . str_replace('\\', '/', $filename));
        return ['width' => $size[0], 'height' => $size[1]];
    }
    
}

controllers/EventController.php
<?php
/**
 * Created by PhpStorm.
 * User: tin
 * Date: 26.11.2017
 * Time: 21:14
 */

namespace app\controllers;

use app\models\Event;
use Yii;
use yii\web\Controller;
use app\models\EventCategory;
use app\models\City;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\imagine\Image;
use Imagine\Image\Box;
use Imagine\Image\Point;
use app\models\RelEventToCategory;

class EventController extends Controller
{
    public function init() {
        if(Yii::$app->user->isGuest) {
            return $this->goHome();
        }
    }

    public function actionAdd() {
        if(isset($_GET['id']) && !empty($_GET['id'])) {
            $model = Event::find()->where(['id' => $_GET['id'], 'user_id' => Yii::$app->user->id])->one();
            foreach(RelEventToCategory::find()->where(['event_id' => $model->id])->all() as $c) 
                $model->category_ids[] = $c->event_category_id;
            if(!$model)
                return $this->goHome();
        } else {
            $model = new Event;
        }
        $category_arr = ArrayHelper::map(EventCategory::getCategoryList(), 'id', 'name');
        $city_arr = ArrayHelper::map(City::find()->orderBy('name ASC')->asArray()->all(), 'id', 'name');
        if($model->isNewRecord)
            $this->view->title = 'Новое мероприятие — YOweekend.ru';
        else 
            $this->view->title = 'Редактирование мероприятия — YOweekend.ru';
        
        $model->user_id = Yii::$app->user->id;
        if(isset($_POST['Event']) && !empty($_POST['Event'])) {
            if($model->load(Yii::$app->request->post()) && $model->validate()) {
                $model->image_original = str_replace("\\", "/", $model->image_original);
                $model->image_preview = str_replace("\\", "/", $model->image_preview);
                //Копируем основное изображение из темповой папки в основную
                $directory = $_SERVER['DOCUMENT_ROOT'].'/media/userimages' . DIRECTORY_SEPARATOR . Yii::$app->user->id . DIRECTORY_SEPARATOR;
                if (!is_dir($directory)) {
                    FileHelper::createDirectory($directory);
                }
		$ext_arr = explode('.', $model->image_original);
                $ext = array_pop($ext_arr);
                $_origin_file_name = uniqid(time(), true) . '.' . $ext;
                copy($_SERVER['DOCUMENT_ROOT'] . $model->image_original, $directory . $_origin_file_name);
                $model->image_original = '/media/userimages' . DIRECTORY_SEPARATOR . Yii::$app->user->id . DIRECTORY_SEPARATOR . $_origin_file_name;
                //Создаем превью размером 300x300
                $imagine = new Image;
                $imagine::getImagine()->open($_SERVER['DOCUMENT_ROOT'] . $model->image_preview)
                    ->crop(new Point($model->x1, $model->y1), new Box(300 , 300))
                    ->save($directory . 'preview_' . $_origin_file_name);
                $model->image_preview = '/media/userimages' . DIRECTORY_SEPARATOR . Yii::$app->user->id . DIRECTORY_SEPARATOR . 'preview_' . $_origin_file_name;                
                if($model->isNewRecord)
                    $model->create_date = date('Y-m-d H:i:s');
                else
                    $model->update_date = date('Y-m-d H:i:s');
                if($model->save()) {
                    RelEventToCategory::deleteAll(['event_id' => $model->id]);
                    foreach($model->category_ids as $id) {
                        $relation = new RelEventToCategory;
                        $relation->event_id = $model->id;
                        $relation->event_category_id = $id;
                        $relation->save();
                        unset($relation);
                    }
                    Yii::$app->session->setFlash('success', 'Ваше мероприятия успешно сохранено, теперь его видят пользователи в ленте.');
                    return $this->redirect('/event/edit/'.$model->id);
                } else {
                    Yii::$app->session->setFlash('error', 'В процессе сохранения произошла ошибка.');
                }
                
            } else {
                Yii::$app->session->setFlash('error', 'В процессе сохранения произошла ошибка.');
            }
        }
        return $this->render('add',[
            'model' => $model,
            'category_arr' => $category_arr,
            'city_arr' => $city_arr,
        ]);
    }
    
    public function actionDelete() {
        if(!Yii::$app->request->isAjax) {
            echo json_encode(['status' => false, 'error' => 'Это не Аякс запрос.']);   
            Yii::$app->end();
        }
        
        $event_id = Yii::$app->request->post('id', 0);        
        $event = Event::find()->where(['id' => $event_id])->one();
        if(!$event) {
            echo json_encode(['status' => false, 'error' => 'По какой-то причине данного мероприятия не существует.']);   
            Yii::$app->end();
        }
        if($event->user_id != Yii::$app->user->id) {
            echo json_encode(['status' => false, 'error' => 'Данное мероприятие принадлежит не вам.']);   
            Yii::$app->end();
        }
        
        if($event->delete()) {
            echo json_encode(['status' => true]);   
            Yii::$app->end();
        } else {
            echo json_encode(['status' => false, 'error' => 'В процессе удаления произошла ошибка']);   
            Yii::$app->end();
        }
    }
}

controllers/MediaController.php
<?php
/**
 * Created by PhpStorm.
 * User: tin
 * Date: 26.11.2017
 * Time: 21:55
 */

namespace app\controllers;

use Yii;
use app\models\Event;
use yii\web\Controller;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\helpers\Json;
use yii\imagine\Image;
use Imagine\Image\Box;

class MediaController extends Controller
{
    public function actionUpload() {                       
        $model = new Event();

        $imageFile = UploadedFile::getInstance($model, 'image');
        if(!in_array($imageFile->getExtension(), ['jpg', 'png', 'jpeg'])) {
            return Json::encode([
                'status' => false,
                'textError' => 'Вы можете загружать только файлы изображений с разрешениями png, jpg, jpeg.'
            ]);
        }

        $directory = $_SERVER['DOCUMENT_ROOT'].'/media/temp' . DIRECTORY_SEPARATOR . Yii::$app->session->id . DIRECTORY_SEPARATOR;
        if (!is_dir($directory)) {
            FileHelper::createDirectory($directory);
        }

        if ($imageFile) {
            $uid = uniqid(time(), true);
            $fileName = $uid . '.' . $imageFile->extension;
            $filePath = $directory . $fileName;
            if ($imageFile->saveAs($filePath)) {
                $path = '/media/temp/' . Yii::$app->session->id . DIRECTORY_SEPARATOR . $fileName;                
                $previewObjSize = $model->getPreviewSize(getimagesize($_SERVER['DOCUMENT_ROOT'].$path));
                $file_preview_path = '/media/temp' . DIRECTORY_SEPARATOR . Yii::$app->session->id . DIRECTORY_SEPARATOR . 'preview_'. $fileName;
                $box = new Box($previewObjSize['width'], $previewObjSize['height']);
                $preview = Image::getImagine()->open($_SERVER['DOCUMENT_ROOT'].$path);
                $preview->resize($box)->save($_SERVER['DOCUMENT_ROOT'].$file_preview_path);
                return Json::encode([
                    'files' => [
                        [
                            'name' => $fileName,
                            'size' => $imageFile->size,
                            'url' => $path,
                            'thumbnailUrl' => $file_preview_path,
                            'deleteUrl' => 'image-delete?name=' . $fileName,
                            'deleteType' => 'POST',
                            'width' => $previewObjSize['width'],
                            'height' => $previewObjSize['height'],
                        ],
                    ],
                ]);
            }
        }
    }
}

views/event/add.php
<?php
use dosamigos\fileupload\FileUpload;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm
?>
<?php
$flash_title = '';
$flash_message = '';
$flash_class = '';
if(!empty(Yii::$app->session->getFlash('error'))) {
    $flash_title = 'Ошибка';
    $flash_message = Yii::$app->session->getFlash('error');
    $flash_class = 'callout-warning';
    Yii::$app->session->removeFlash('error');
} 
if(!empty(Yii::$app->session->getFlash('success'))) {
    $flash_title = 'Успех!';
    $flash_message = Yii::$app->session->getFlash('success');
    $flash_class = 'callout-success';
    Yii::$app->session->removeFlash('success');
}

?>
<? if(!empty($flash_message)): ?>
    <div class="callout <?= $flash_class ?>" style="">
            <h4><i class="fa fa-info"></i> <?= $flash_title?></h4>
            <?= $flash_message ?>
    </div>
<? endif; ?>
<?php $form = ActiveForm::begin(); ?>
    <div class="form-group">
        <label>Афиша</label>
        <div class="input-group">
            <!-- <button class="btn btn-primary btn-sm">Загрузить изображение</button> -->
            <?= FileUpload::widget([
                'model' => $model,
                'attribute' => 'image',
                'url' => ['media/upload'], // your url, this is just for demo purposes,
                'options' => [
                    'accept' => 'image/*',
                ],                
                'clientOptions' => [
                    'maxFileSize' => 2000000,
                    'dataType' => 'json',
                ],
                // Also, you can specify jQuery-File-Upload events
                // see: https://github.com/blueimp/jQuery-File-Upload/wiki/Options#processing-callback-options
                'clientEvents' => [
                    'fileuploaddone' => 'function(e, data) {
                                if(typeof(data.result.status) != undefined && data.result.status == false) {
                                    show_info_modal("Ошибка!", data.result.textError);
                                } else {
                                    $(".field-event-image_original").removeClass("has-error");
                                    $(".field-event-image_original p").empty();
                                    $("#event-image_original").val(data.result.files[0].url);
                                    $("#event-image_preview").val(data.result.files[0].thumbnailUrl);
                                    $(".object-image").imgAreaSelect( {remove: true} );
                                    $(".object-image").attr("src", data.result.files[0].thumbnailUrl).imgAreaSelect({                                       
                                        handles: true,
                                        onSelectEnd: setImgCoordinates,
                                        onInit: setImgCoordinates,
                                        minWidth: 299,
                                        minHeight: 299,
                                        maxWidth: 300,
                                        maxHeight: 300,
                                        show: true,
                                        imageHeight: data.result.files[0].height,
                                        imageWidth: data.result.files[0].width,
                                        x1: 0,
                                        x2: 298,
                                        y1: 0,
                                        y2: 298,
                                    });
                                }
                            }',
                    'fileuploadfail' => 'function(e, data) {
                                console.log(e);
                                console.log(data);
                                show_info_modal("Ошибка!", "В процессе загрузки файла произошла ошибка");
                            }',
                ],
            ]); ?>
            <div class="img_preview">
                <? $img_size = $model->getRealImgSize($model->image_preview);?>
                <img class="img-responsive object-image" src="<?= $model->image_preview ?>" data-real-width="<?= $img_size['width']?>" data-real-height="<?= $img_size['height']?>">
            </div>
        </div>
    </div>
    <?= $form->field($model, 'image_original')->hiddenInput()->label(false); ?>
    <?= $form->field($model, 'image_preview')->hiddenInput()->label(false); ?>
    <?= $form->field($model, 'x1')->hiddenInput()->label(false); ?>
    <?= $form->field($model, 'x2')->hiddenInput()->label(false); ?>
    <?= $form->field($model, 'y1')->hiddenInput()->label(false); ?>
    <?= $form->field($model, 'y2')->hiddenInput()->label(false); ?>

    <?= $form->field($model, 'name')->textInput() ?>
    <?= $form->field($model, 'category_ids', [
            'template' => '{label}{input}{error}{hint}<a href="#" data-toggle="modal" data-target="#add-new-category">Если вы не нашли свою категорию, нажмите на эту ссылку</a>'
        ])->dropDownList($category_arr, ['class' => 'form-control select2', 'multiple' => true, 'aria-hidden' => true])?>
    <?= $form->field($model, 'link')->textInput() ?>
    <?= $form->field($model, 'city_id')->dropDownList($city_arr, ['class' => 'form-control select2', 'multiple' => false, 'aria-hidden' => true])?>
    <?= $form->field($model, 'address')->textInput() ?>
    <?= $form->field($model, 'meeting_date', [
        'template' => '{label}<div class="input-group"><div class="input-group-addon"><i class="fa fa-calendar"></i></div>{input}</div>{error}{hint}'
    ])->textInput(['class' => 'form-control datepicker-modal', 'data-inputmask' => "'alias': 'dd/mm/yyyy'", 'data-mask' => "", "readonly" => true]) ?>
    <div class="bootstrap-timepicker">
        <?= $form->field($model, 'time_begin', [
            'template' => '{label}<div class="input-group"><div class="input-group-addon"><i class="fa fa-clock-o"></i></div>{input}</div>{error}{hint}'
        ])->textInput(['class' => 'form-control input-small timepicker', "readonly" => true]) ?>
        <?= $form->field($model, 'no_time')->checkbox(['class' => 'minimal', 'value' => '1'])->label('Не показывать время на сайте (не желательно)', ['class'=> 'draft-checkbox-label']); ?>
    </div>
    <?= $form->field($model, 'price', [
            'template' => '{label}<div class="input-group"><div class="input-group-addon"><i class="fa fa-rub"></i></div>{input}<span class="input-group-addon">.00</span></div>{error}{hint}'
        ])->textInput() ?>
    <?= $form->field($model, 'description')->textarea(['rows' => 10]) ?>
    <?= $form->field($model, 'isDraft')->checkbox(['class' => 'minimal', 'value' => '1'])->label('Черновик', ['class'=> 'draft-checkbox-label']); ?>
    <div class="form-group col-lg-2 col-md-2 col-sm-2 col-xs-6" style="padding-left: 0; ">
        <button type="submit" class="btn btn-block btn-primary btn-flat">Сохранить</button>
    </div>
<?php ActiveForm::end(); ?>
<div class="modal fade in" id="add-new-category">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div class="callout" style="display: none;">
                        <h4><i class="fa fa-info"></i></h4>
                        <span>dfgdfg</span>
                </div>
                <form>
                    <div class="form-group category-name required">
                        <label class="control-label" for="category-name">Введите название предлагаемой категории</label>
                        <input type="text" class="form-control">
                        <p class="help-block help-block-error"></p>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary pull-left" id="send-new-category">Отправить</button>
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>